### ISSUE TITLE
Remove redundant mods (?)

### ISSUE THREAD

**Issue by HyperSoop** [modrinth-smp/pack#15]
There are some mods in the pack which are to say it lightly not very relevant. I made this issue to point out some mods which are (i think) not relevant to the player for the most part and removing which could improve stability and ease matienace.

okay all below is open to discussion and is my personal opinion 

1. Impaled (its throwables do not go well with Enhancement's changes + all of the new things it adds are just the same trident!)
2. Numismatic Overhaul (this is a very good concept, but the only thing the coins are used for is villager trading + the only way to get them is killing illagers? unless we have more mods that integrate with it, it's not worth the broken balance and used inventory screen space)
3. Rat's Mischief (have you ever seen a rat in your world? it also is the only mod to require GeckoLib (a very specific version too), correct me if I'm wrong)

also some things that are just visual most of the time and have too little of an impact:

4. Rainglow (it could be a client-only mod, if it's not, why bother...?)
5. W.O.O.F (it's mostly visual. It does add some items, but those are just cosmetics. If it had a levelling system/skill trees for pets and protection for them from the owner's attacks, maybe, but in the current state it's only cosmetic.

**Comment by Gaming32** [comment]
1) The different tridents have different abilities. Also the pitchfork is very easy to obtain. Also I had to get the dev's permission for it.
2) I have coins that I got from chests, but yeah, it's not great.
3) I love Rat's Mischief. Especially those Elytrats. 
4) No, Rainglow is great. 
5) The developer literally ported W.O.O.F. so that we could use it.

**Comment by HyperSoop** [comment]
1, 5; it's the initial decision that should have been debated then. i do understand keeping them due to the effort required to obtain them.

**Comment by jadelily18** [comment]
I can definitely agree with Numismatic Overhaul, but I definitely disagree with the others.

Adding on a bit to some of the reasons that Gaming32 stated:
* Rainglow is a great mod!! Some features of it require it on the server, and I don't really see any reason to remove it because of that.
* W.O.O.F. is also a great mod. It is mostly cosmetic, but it adds some stuff I believe a lot of players like. (plus yeah it was ported pretty much specifically to be in this pack. Removing it now would be a slap in the face to mineblock11 and either way, I don't see any reason to remove it)

A big issue with the pack for me right now is that some things feel completely incompatible and some things feel very unpolished, and I think we need to work on that. I just don't think anything you recommended besides the removal of Numismatic Overhaul would really help.

**Comment by HyperSoop** [comment]
At least 20% of what I said was reasonable. Nice

**Comment by intergrav** [comment]
> A big issue with the pack for me right now is that some things feel completely incompatible and some things feel very unpolished, and I think we need to work on that. I just don't think anything you recommended besides the removal of Numismatic Overhaul would really help.

One of the main reasons I dislike most kitchen-sink modpacks actually
